runtime: python
env: flex
manual_scaling:
  instances: 1
entrypoint: gunicorn -b 0.0.0.0:8080 server:app
runtime_config:
  python_version: 3
env_variables:
  GCLOUD_BUCKET: '[flask-api-ey-341014]-media'
